import type { Metadata } from "next";
import "./globals.css";
import { VisualEditsMessenger } from "orchids-visual-edits";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import FloatingContactButtons from "@/components/ui/floating-contact-buttons";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="antialiased"
        suppressHydrationWarning
      >
        {children}
        <FloatingContactButtons />
        <VisualEditsMessenger />
      </body>
    </html>
  );
}
